stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: "aron666/aron.grassminer"
  TAG_LATEST: "test"

# 定義 Docker login 的全局設置
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build-amd64:
  stage: build
  tags:
    - amd64
  image: docker # 使用 Docker 官方鏡像
  services:
    - docker:dind # 使用 Docker-in-Docker
  script:
    - cd Aron.GrassMiner
    - docker build --build-arg TARGETARCH=amd64 -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:$TAG_LATEST # 標記為 latest
  only:
    - develop # 僅當該分支有變更時觸發


build-arm64:
  stage: build
  tags:
    - arm64
  image: docker
  services:
    - docker:dind
  script:
    - cd Aron.GrassMiner
    - docker build --build-arg TARGETARCH=arm64 -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:$TAG_LATEST
  only:
    - develop


push-image:
  stage: push
  image: docker
  services:
    - docker:dind
  script:
    - docker push $IMAGE_NAME:$TAG_LATEST
  only:
    - develop
