version: '1'
services:
  grass:
    image: aron666/aron.grassminer
    environment:
      - GRASS_USER=user
      - GRASS_PASS=password
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
    ports:
      - 5001:8080
    build: 
      context: .
      dockerfile: Dockerfile
