version: '1'
services:
  grassminer:
    image: aron666/aron.grassminer
    container_name: grassminer
    environment:
      - GRASS_USER=user
      - GRASS_PASS=password
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
    ports:
      - 5001:8080
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules
    stdin_open: true
    tty: true
